---
deployment:
  tasks:
    - /bin/cp -R index.html /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R terms-conditions.html /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R sales-conditions.html /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R legal-mentions.html /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R sitemap.xml /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R robots.txt /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R css /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R js /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R images /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R .htaccess /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R fr /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R es /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R de /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R ru /home/weve4332/longtailboat-kohsamui.com/
    - /bin/cp -R zh /home/weve4332/longtailboat-kohsamui.com/
